services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./migrations:/app/migrations
      - ./src:/app/src
      - ./main.py:/app/main.py
    env_file:
      - ./.env.template
    ports:
      - "8000:80"
    networks:
      - todo-command-network

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_todo_command_data:/var/lib/postgresql/data
    networks:
      - todo-command-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - todo-command-network

networks:
  todo-command-network:
    driver: bridge

volumes:
  postgres_todo_command_data:
