services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/app/:rw
    networks:
      - app-network
    environment:
      - ENVIRONMENT=local
      - AWS_ENDPOINT_URL=http://motoserver:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION_NAME=us-east-1
      - AWS_COGNITO_APP_CLIENT_ID=test
      - AWS_COGNITO_USER_POOL_ID=test
      - AWS_COGNITO_JWK_URI=http://motoserver:4566/{userpoolid}/.well-known/jwks.json
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    depends_on:
      - motoserver

  motoserver:
    image: motoserver/moto:latest
    ports:
      - "4566:4566"
    environment:
      - MOTO_PORT=4566
    networks:
      - app-network

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./infra/aws/setup:/infra:rw
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
    networks:
      - app-network
    depends_on:
      - motoserver

networks:
  app-network:
    driver: bridge
