# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Prevents Python from writing pyc files to disc (equivalent to python -B option)
ENV PYTHONDONTWRITEBYTECODE=1
# Prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Command to run the FastAPI application with Uvicorn
CMD ["python", "-m", "pytest", "tests", "-s". "-vv", "-x"]
