services:
  tests:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    volumes:
      - .:/app/
    command: |
      python -m pytest tests -s -vv -x --cov --cov-report=html:/app/reports/coverage --alluredir /app/allure-results
    env_file:
      - .env.test.template

  allure:
    build:
      context: ./app
      dockerfile: Dockerfile.allure
    volumes:
      - .:/app/
    ports:
      - "35741:35741"
