FROM node:8.1.4-alpine

WORKDIR /app

RUN apk add --no-cache make gcc g++ python openjdk8

RUN yarn global add allure-commandline && \
  apk del make gcc g++ python

EXPOSE 35741

CMD [ "allure", "serve", "-p", "35741", "allure-results" ]
